thecodrr/fdir

index.d.ts
Since both functions use `options = {}` there's no need to force the options argument.
This now allows the following.
```ts
import * as fdir from 'fdir';
fdir.async('/').then(files => {
console.log(files);
});
```
Where as before you'd need to pass an empty second param.
```ts
import * as fdir from 'fdir';
fdir.async('/', {}).then(files => {
console.log(files);
});
```
=> Make options arg optional.

index.d.ts
`String` is the string constructor.
If you're wanting a string like `''`, `""`, or ``` `` ``` then you need to use `string`.
=> use the correct string type

__tests__/fdir.test.js, documentation.md, index.d.ts, src/api/fns.js, src/api/shared.js, src/builder/index.js
It is now possible to add multiple filters like:
```js
new fdir().filter(p => p.endsWith(".js")).filter(p => p.startsWith(".nim"))
```
Obviously, you can also do that in a single filter but I think it allows for better readability. The performance hit is also negligible.
=> feat: add support for multiple filters

README.md
> > creating an issue, becoming a stargazer or opening
>
>  creating an issue, becoming a stargazer, or opening
In English, the Nightmare Language &trade;, you put commas between all fields unless fewer than three.  This is called "The Oxford Comma," because people from Oxford got in so many fights about this that it was named after them.
The standard explanation is "I have a time machine.  I brought the drinks, the poison and the antimatter."  Without the comma, the drinks *are* the poison and the antimatter.  With the comma, they're all distinct things.
.
> > I have written an in-depth documentation
> 
> I have written in-depth documentation
"Documentation" is inherently plural (the singular is document.)  Therefore, you didn't write one of them, so "an" is unnecessary.
.
> **Specs:** …
=> Grammar edits.

documentation.md, index.d.ts, src/api/async.js, src/api/fns.js, src/api/shared.js, src/api/sync.js, src/builder/index.js
Hello, this PR fixes a few issues!
* Fixes #42
* I used `'\0'` instead of `'||'` because `\0` is the only character that cannot ever appear in a file path, cross-platform, so no one should ever use that in any glob pattern, while `'||'` could in theory appear in a glob pattern, possibly.
* Fixes #47
* Closes #46
=> Fix #42, #46 and #47

__tests__/fdir.test.js, documentation.md, index.d.ts, src/api/async.js, src/api/fns.js, src/api/queue.js, src/api/shared.js, src/builder/index.js, src/compat/fs.js
Closes #53 
Symlinks are resolved using a combination of `realpath` & `lstat`. Since fdir supports both sync & async APIs, I had to add a basic queue system.
**`Queue`**:
Queue works by incrementing a counter everytime an async call is made and decrementing it once it is done. Once the counter === 0, it invokes the `onQueueEmpty` callback.
> This allows us to use async functions with callbacks almost anywhere.
**TODO**:
1. There are no tests for the symlinks support.
2. Internal function naming in fdir is all over the place. (this will be done in a separate PR)
=> Implement symlinks support

package.json
This will allow adopting libraries use `picomatch` without error and without it being a required dependency to install.
=> Add picomatch in peerDependencies

package.json
Building off of https://github.com/thecodrr/fdir/pull/76, this makes picomatch an optional peer dependency, to avoid it from being automatically installed by some package managers, or throwing warnings in others.
@thecodrr I'd love if you could take a look at this and hopefully merge and release a new version soon, so it can unblock me on https://github.com/storybookjs/storybook/pull/19297 in adding this library to Storybook.
=> Make picomatch an optional dependency

__tests__/fdir.test.js, documentation.md, index.d.ts, src/api/fns.js, src/api/walker.js, src/builder/index.js
This adds a new builder method `withRealPaths` which should give the previous behavior. By default symlinked paths will not be resolved.
Closes #83
=> Add support for returning symlinked paths

package-lock.json, package.json
didn't drop picomatch v3 to avoid breaking changes
fixes #96
=> feat: add support for picomatch v4

__tests__/fdir.test.ts, benchmarks/benchmark.js, index.ts, src/index.ts, tsconfig.json
Closes #102. Should reduce the total bundle size by 30.5% :O
=> chore: exclude irrelevant files from published bundle

README.md
The legacy Immich CLI is no longer available, remove dead link. The new Immich CLI uses another library
=> fix(docs): remove Immich CLI

benchmarks/fdir-benchmark.ts, benchmarks/glob-benchmark.ts
=> chore: fix import in benchmark scripts

__tests__/fdir.test.ts, documentation.md, src/api/functions/resolve-symlink.ts, src/builder/index.ts, src/types.ts
While working on `tinyglobby` I've noticed there is no way to disable `fdir` returning the real path of a symlink anymore, due to #81 silently removing support for it (even though the documentation still mentions the feature!).
This PR adds it back, inside an object parameter instead for better API design (see https://github.com/thecodrr/fdir/issues/83#issuecomment-1282787956). It defaults to `true` for backwards compatibility
Closes #103
=> feat: add `withSymlinks` argument back

README.md
There are a few well-known packages that use `fdir`. I listed them first because I've heard of them and haven't really heard of most of the other ones in the list
https://www.npmjs.com/package/miniprogram-to-uniapp has only 28 downloads / week, so I removed it
I left `astro-i18next`, which has about 1,800 downloads/week, but wasn't sure if we still needed it now that `astro` itself is being listed
=> docs: list more packages using `fdir`

__tests__/fdir.test.ts, documentation.md, src/api/functions/resolve-symlink.ts, src/api/walker.ts, src/types.ts
when `resolveSymlinks` is not set, symlinks just get treated as files. this adds support for individually excluding symlinks from the result
why? because fdir currently has ways of excluding files and directories, but not symlinks (and also because it was requested in SuperchupuDev/tinyglobby#26)
=> feat: add support for excluding symlinks

__tests__/fdir.test.ts, documentation.md, src/builder/index.ts, src/types.ts
This allows you to pass in your own `globFunction` rather than picomatch, so we're not forcing a choice here (someone may want to use a simpler library or a newer picomatch).
Example:
```ts
function globFunction(
patterns: string | string[],
) {
return (test) => {
// some glob match logic
};
}
const api = new fdir({globFunction})
.glob('*.js')
.crawl(cwd);
const files = await api.withPromise();
```
benchmark seems to be about the same as before on my machine
this also means the options stay strongly typed for whatever glob function you use i think. some example of that:
```ts
interface GlobOptions {
x: number;
}
declare function globFunction(patterns: string|string[], options?: GlobOptions): GlobMatcher;
const api = new fdir({globFunction});
api.globWithOptions(
['*.js'],
{
x: 100, // …
```
=> feat: allow custom glob functions other than picomatch

__tests__/fdir.test.ts, documentation.md, src/api/functions/join-path.ts, src/api/walker.ts
fixes #113
when investigating, i found out that the issue was caused by the following line:
https://github.com/thecodrr/fdir/blob/5a0aab5b3e108eaf677e0e39c22ff1ea03cd1a59/src/api/walker.ts#L120-L121
with relative paths on, `path` won't be an absolute path, and as such will be resolved in the `stat` call as a path relative to `process.cwd()`. this makes it throw an `ENOENT` error (unless the symlink happens to be located in `process.cwd()`). i fixed this by changing the declaration to make it an absolute path instead.
just fixing this line wasn't enough though, because the `resolvedPath` seems to always be absolute. to fix this, i did a substring transformation to a relative path (if the symlink is a file) if the `relativePaths` option is enabled and `useRealPaths` is `false`. the latter …
=> fix: support symlinks without real paths with relative paths enabled

__tests__/fdir.test.ts, src/api/functions/push-directory.ts, src/builder/index.ts
also adds more tests that are related to `pushDirectory`, and corrects the type of `.crawl`'s argument
doing this, the project is fully covered by tests except for the error handling in `resolveSymlinks`, that i am not sure how to hit
=> fix: do not return an empty string for the root

__tests__/fdir.test.ts, __tests__/symlinks.test.ts, __tests__/utils.ts, src/api/functions/resolve-symlink.ts, src/api/functions/walk-directory.ts, src/api/walker.ts, src/types.ts
=> Fix recursive symlinks causing infinite loop

__tests__/symlinks.test.ts, src/api/walker.ts
see the e18e discord for discussion, sorry i didn't have time to open an issue
the exclude predicate always used real paths on symlinks, this should fix that
=> fix: do not incorrectly use real paths on exclude predicate

documentation.md
Passing only the "files" parameter doesn't seem to work. The change mimicks parameters shown in test at https://github.com/thecodrr/fdir/blob/1f4eece91127359619c46c359606a6c3294fc5b7/__tests__/fdir.test.ts#L18.
=> Update documentation for withCallback()

__tests__/symlinks.test.ts, src/api/walker.ts
Fixes #135.
The current behavior makes it so that when we're crawling `"/"` with some symlinks and `resolvePath: false`, `state.root` is an empty string in https://github.com/thecodrr/fdir/blob/e2d5c86fc924cd6aba8053615dd7b73001726f7d/src/api/functions/resolve-symlink.ts#L75, hence we get stuck in an infinite loop.
Tests pass locally both on Linux (WSL) and Windows.
=> Fix hang when crawling root with direct symlinks

__tests__/symlinks.test.ts, src/api/walker.ts, src/utils.ts
I'm confused as I could've sworn I ran the tests locally on Windows in https://github.com/thecodrr/fdir/pull/137, but maybe I was in WSL all along. In any case, this PR fixes the hang by properly handling Windows root directory paths.
=> fix: correct #137 hanging the tests on Windows

.github/workflows/run-tests.yml
I just kept the oldest and latest Node versions to save your CI budget
=> chore: test against Node 24 and update GitHub Actions

__tests__/fdir.test.ts, src/api/functions/walk-directory.ts, src/api/queue.ts, src/api/walker.ts, src/types.ts
Fixes #143 
This PR fixes multiple issues with the `queue/enqueue` logic ensuring:
- `onQueueEmpty` is called only once
- The crawler aborts on error (before it kept crawling which was pointless)
Another change I had to make was how the crawler always returned results `maxDepth + 1` deep. This might break some things (but not really sure since all tests pass).
cc @SuperchupuDev can you test this out with `tinyglobby` and let me know if something breaks?
=> Ensure callback is called only once

__tests__/fdir.test.ts, src/api/functions/walk-directory.ts
fixes #148, it looks like the depth tests only tested against an upper bound and not a lower one, and as such i've updated them
=> fix: do not stop crawling at `currentDepth` 0

src/api/functions/join-path.ts
Potential improvement found while working on #151. Tested with the following script:
```js
const path = "/some/very/long/path/to/a/directory";
const root = "/some/very/long/path/";
console.time("slice");
for (let i = 0; i < 1_000_000; i++) {
const result = path.slice(root.length);
}
console.timeEnd("slice");
console.time("replace");
for (let i = 0; i < 1_000_000; i++) {
const result = path.replace(root, "");
}
console.timeEnd("replace");
```
```
slice: 5.921ms
replace: 24.304ms
```
=> perf: use `slice` instead of `replace` when joining path

__tests__/fdir.test.ts, src/api/aborter.ts, src/api/walker.ts, src/builder/index.ts, src/types.ts
This is only a workaround until we can drop support for Node v14. Since AbortController is not exposed anywhere, we can replace it with a custom implementation.
=> Drop AbortController as it breaks fdir on Node v14

src/api/walker.ts
#136 used the `??` operator (probably on accident) which would break node compat again :sweat_smile: tiny change but important
=> fix: use `||` instead of `??` for node 12 compat

package-lock.json, package.json, src/builder/index.ts
`@types/picomatch` v4 makes `Matcher` have an optional second argument. if set to `true`, it makes the function return some object and not a string. This breaks `fdir`'s types. To fix this, I replaced it with the already used `GlobMatcher` type that's identical to `Matcher` except it doesn't require a second argument (this makes sense to use since, if the second argument was used, fdir would break at runtime since it doesn't expect an object)
Ideally #147 should be merged first to avoid causing merge conflicts on that pr :pray:
For prior work see SuperchupuDev/tinyglobby@f2419f8
Also makes `picomatch` importing have modern syntax. It doesn't break any compatibility, everything changed works starting from node 10. And fdir supports node 12 and up (manually checked)
=> fix: support `@types/picomatch` v4
